Update Tutorial Readme
msupply-foundation/notify pull request #298
Opened 2024-12-10 20:47 UTC by aimee-mcneil-melville

Closes #

# 👩🏻‍💻 What does this PR do?
 
Add subheadings for sections within the main steps
Update images of the schema view in browser
Additional info re the Default trait

More changes to come from the team!

# 🧪 How has/should this change been tested?

## 💌 Any notes for the reviewer?

## 📃 Documentation

This is the docs!

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

2024-12-20 04:35 UTC, lache-melvin requested changes
Couple link fixes - is this still in draft because more changes are planned?

2024-12-20 04:35 UTC, lache-melvin commented on docs/tutorial/1.adding_a_field.md
> +Using `cargo check` you should now be able to find all the places that need to be updated to include the new nickname field in the `UpdateUserAccount` struct. You might want to implement the [Default
```suggestion
Using `cargo check` you should now be able to find all the places that need to be updated to include the new nickname field in the `UpdateUserAccount` struct. You might want to implement the [Default](#default-data) trait for this struct too, so that you don't need to update all the test cases next time..
```

2024-12-20 04:35 UTC, lache-melvin commented on docs/tutorial/1.adding_a_field.md
> +This can be done with the [Diesel CLI tool](https://crates.io/crates/diesel_cli){:target="\_blank"}.
```suggestion
This can be done with the [Diesel CLI tool](https://crates.io/crates/diesel_cli).
```
Currently rendering like this, but probably fine without?
![Screenshot 2024-12-20 at 5 31 00 PM](https://github.com/user-attachments/assets/b1c2b56b-e6d0-47aa-9ece-555d7f480ab2)

2025-01-19 23:34 UTC, noel-yeldos commented on docs/tutorial/1.adding_a_field.md
> +Using `cargo check` you should now be able to find all the places that need to be updated to include the new nickname field in the `UpdateUserAccount` struct. You might want to implement the [Default
Updated here 5f8e3080f6916db70046e23ce177ecfd8b9210c4

2025-01-19 23:34 UTC, noel-yeldos commented on docs/tutorial/1.adding_a_field.md
> +This can be done with the [Diesel CLI tool](https://crates.io/crates/diesel_cli){:target="\_blank"}.
Updated here 04476f1de3f647a92958b4ae2d69a01083cb27e0

2025-01-20 02:05 UTC, jmbrunskill approved these changes
Thanks for the updates!
Could of suggestions added but looks like improvments :)

2025-01-20 02:05 UTC, jmbrunskill commented on docs/tutorial/1.adding_a_field.md
> +By default, diesel_cli requires a set of features, which includes several not used in Notify. This command specifies that diesel_cli will only depend on postgres and sqlite.
```suggestion
By default, diesel_cli includes features for databases such as mysql that are not used in Notify. This command specifies that diesel_cli will only depend on postgres and sqlite.
```

2025-01-20 02:05 UTC, jmbrunskill commented on docs/tutorial/1.adding_a_field.md
> +Effectively, using the default trait means that most of our mock user accounts won't have a nickname. Their nickname will be set to `None`.
```suggestion
Using the default trait means that most of our mock user accounts won't have a nickname. Their nickname will be set to `None`.
```

2025-01-20 02:11 UTC, lache-melvin approved these changes
Looks great! Agree with James, thanks Noel and Aimee 🙏

2025-01-20 23:56 UTC, noel-yeldos commented on docs/tutorial/1.adding_a_field.md
> +### Generate function
Updated here 0da20c64c862c1bb71e98742d6d0c5a87a68503a

2025-01-20 23:56 UTC, noel-yeldos commented on docs/tutorial/1.adding_a_field.md
> +You may need to add `Default` as a trait in the struct in your `create.rs` file
Updated here 0da20c64c862c1bb71e98742d6d0c5a87a68503a

2025-01-20 23:56 UTC, noel-yeldos commented on docs/tutorial/1.adding_a_field.md
> +By default, diesel_cli requires a set of features, which includes several not used in Notify. This command specifies that diesel_cli will only depend on postgres and sqlite.
Updated here 0da20c64c862c1bb71e98742d6d0c5a87a68503a

2025-01-20 23:56 UTC, noel-yeldos commented on docs/tutorial/1.adding_a_field.md
> +Effectively, using the default trait means that most of our mock user accounts won't have a nickname. Their nickname will be set to `None`.
Updated here 0da20c64c862c1bb71e98742d6d0c5a87a68503a

2025-01-20 23:59 UTC, lache-melvin approved these changes
merge it!

2025-01-21 00:01 UTC, merged